---
title: "PLS Libs not in 2022 USAC"
output: html_notebook
---

```{r}
library(RSocrata)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(aws.s3)
```

```{r}
erate_imls <- s3read_using(FUN = read.csv, object = "data/AVI8-SVP9_Commitments/Libraries_Funded_Committed_AVI8-SVP9_with_FSCS_Matches.csv", bucket = "erate-data")

# Read in IMLS PLS dataset stored in S3
full_imls <- s3read_using(FUN = read.csv, object = "data/IMLS_PLS/2014-2020_OUTLETs_and_AEs_Merged.csv", bucket = "erate-data")

# Read in IMLS PLS AE datasets stored in S3
imls_ae_2020 <- s3read_using(FUN = read.csv, object = "data/IMLS_PLS/2020_IMLS_PLS_AE.csv", bucket = "erate-data")
imls_ae_2019 <- s3read_using(FUN = read.csv, object = "data/IMLS_PLS/2019_IMLS_PLS_AE.csv", bucket = "erate-data")
imls_ae_2018 <- s3read_using(FUN = read.csv, object = "data/IMLS_PLS/2018_IMLS_PLS_AE.csv", bucket = "erate-data")
imls_ae_2017 <- s3read_using(FUN = read.csv, object = "data/IMLS_PLS/2017_IMLS_PLS_AE.csv", bucket = "erate-data")
imls_ae_2016 <- s3read_using(FUN = read.csv, object = "data/IMLS_PLS/2016_IMLS_PLS_AE.csv", bucket = "erate-data")
imls_ae_2015 <- s3read_using(FUN = read.csv, object = "data/IMLS_PLS/2015_IMLS_PLS_AE.csv", bucket = "erate-data")
imls_ae_2014 <- s3read_using(FUN = read.csv, object = "data/IMLS_PLS/2014_IMLS_PLS_AE.csv", bucket = "erate-data")
```

```{r}
imls_ae <- imls_ae_2014 %>% 
  select(FSCSKEY, POPU_LSA) %>% 
  mutate(POPU_LSA_YEAR = 2014) %>% 
  full_join(imls_ae_2015 %>% 
              select(FSCSKEY, POPU_LSA) %>% 
              mutate(POPU_LSA_YEAR = 2015)) %>% 
  full_join(imls_ae_2016 %>% 
              select(FSCSKEY, POPU_LSA) %>% 
              mutate(POPU_LSA_YEAR = 2016)) %>% 
  full_join(imls_ae_2017 %>% 
              select(FSCSKEY, POPU_LSA) %>% 
              mutate(POPU_LSA_YEAR = 2017)) %>% 
  full_join(imls_ae_2018 %>% 
              select(FSCSKEY, POPU_LSA) %>% 
              mutate(POPU_LSA_YEAR = 2018)) %>% 
  full_join(imls_ae_2019 %>% 
              select(FSCSKEY, POPU_LSA) %>% 
              mutate(POPU_LSA_YEAR = 2019)) %>% 
  full_join(imls_ae_2020 %>% 
              select(FSCSKEY, POPU_LSA) %>% 
              mutate(POPU_LSA_YEAR = 2020))
```


```{r}
IMLS_AE_DISTINCT <- imls_ae %>% 
  group_by(FSCSKEY) %>%
  slice_max(POPU_LSA_YEAR, n=1)
```


```{r}
# Add in LOCALE Descriptions to full_imls
full_imls <- full_imls %>% 
  mutate(
    LOCALE_ADD_DESCR = case_when(
      LOCALE_ADD == 11 ~ "City Large",
      LOCALE_ADD == 12 ~ "City Midsize",
      LOCALE_ADD == 13 ~ "City Small",
      LOCALE_ADD == 21 ~ "Suburban Large",
      LOCALE_ADD == 22 ~ "Suburban Midsize",
      LOCALE_ADD == 23 ~ "Suburban Small",
      LOCALE_ADD == 31 ~ "Town Fringe",
      LOCALE_ADD == 32 ~ "Town Distant",
      LOCALE_ADD == 33 ~ "Town Remote",
      LOCALE_ADD == 41 ~ "Rural Fringe",
      LOCALE_ADD == 42 ~ "Rural Distant",
      LOCALE_ADD == 43 ~ "Rural Remote",
      LOCALE == 11 ~ "City Large",
      LOCALE == 12 ~ "City Midsize",
      LOCALE == 13 ~ "City Small",
      LOCALE == 21 ~ "Suburban Large",
      LOCALE == 22 ~ "Suburban Midsize",
      LOCALE == 23 ~ "Suburban Small",
      LOCALE == 31 ~ "Town Fringe",
      LOCALE == 32 ~ "Town Distant",
      LOCALE == 33 ~ "Town Remote",
      LOCALE == 41 ~ "Rural Fringe",
      LOCALE == 42 ~ "Rural Distant",
      LOCALE == 43 ~ "Rural Remote"
    )) %>% 
  # separate to create high-level category
  # https://stackoverflow.com/a/53701998
  separate(LOCALE_ADD_DESCR, 
        into = c("LOCALE_TOP_LEVEL_DESCR", NA),
        sep = " ",
        remove = F)
```


```{r}
USAC_22_DISTINCT <- erate_imls %>% 
  filter(funding_year == '2022') %>% 
  distinct(FSCSKEY, FSCS_SEQ)
```

```{r}
PLS_DISTINCT <- full_imls %>% 
  distinct(FSCSKEY, FSCS_SEQ)
```

```{r}
non_matches <- anti_join(PLS_DISTINCT, USAC_22_DISTINCT, by = c("FSCSKEY", "FSCS_SEQ"))
```

```{r}
non_matches <- non_matches %>% 
  left_join(full_imls %>%
              group_by(FSCSKEY, FSCS_SEQ) %>%
              slice_max(PLS_YEAR, n=1) %>%
              select(FSCSKEY, FSCS_SEQ, STABR, LIBID, LIBNAME, ADDRESS, CITY, ZIP, LOCALE_ADD, LOCALE, LOCALE_ADD_DESCR, LOCALE_TOP_LEVEL_DESCR, LONGITUD, LATITUDE, PLS_YEAR),
            by = c("FSCSKEY", "FSCS_SEQ")
  )
```

```{r}
non_matches <- non_matches %>% 
  left_join(IMLS_AE_DISTINCT, by = "FSCSKEY")
```

```{r}
write.csv(non_matches, "~/Documents/GitHub/E-Rate/Data/PLS_libs_Not_in_2022_Erate.csv")
```

